### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/madoop#31]
Move the Hadoop Streaming tutorial from the P5 repo to this repo.

## TODO
- [x] Copy Hadoop streaming tutorial to here
- [x]  Edit tutorial to use the word count example distributed with Madoop
- [x] Edit Madoop word count code and input to match P5 example
- [x] Add instructions for how to download the word count example using `wget`
- [x] Update links in p5 spec and remove tutorial from P5 spec
- [x] Update link on eecs485.org
- [x] Update link in Madoop README

**Comment by jaredzh** [comment]
I'm a little confused on the second and third items, don't they conflict with one another? Which word count code and input should be used in the tutorial and the example? The one from P5 or the one currently in `example`?

**Comment by awdeorio** [comment]
> Edit tutorial to use the word count example distributed with Madoop

You're right, this is confusing!  What I meant is to edit the file paths in the Hadoop Streaming tutorial so that students can find the correct input/output files in the Madoop `example/` directory.

> Edit Madoop word count code and input to match P5 example

You're right, this is already done.
